### ISSUE TITLE
Where should I install the scripts?

### ISSUE THREAD

**Issue by Havokdan** [luadch/scripts#16]
Where should I install the scripts? I put them in the "scripts" folder of the luadch, however the commands do not appear, can anyone help me?

**Comment by Havokdan** [comment]
> After you have placed the script files in the right folders you need to tell Luadch to execute the script by adding it in the cfg.tbl. Look at the end of the file and you will find this:

       --// add here your additional scripts

        "etc_requests.lua",

        --------------------------------------
Here i have used etc_requests.lua as an example.
You can then use the command +reload and Luadch will load all scripts without shutting down the hub. Remember that you need to reconnect to get the hub tab menu (right click menu).

Thanks, I'll try it here. I could leave the instructions like this on the main page of this repository, it would be nice.

**Comment by Sopor-** [comment]
Before starting a hub you should read the whole cfg.tbl. Those instructions are already mention on the Luadch page:
```
After this first test you should adapt the hub to your needs:

open: “cfg/cfg.tbl” with a UTF-8 compatible Texteditor best with Lua syntax highlighting
Read the descriptions and set the values to your need, Luadch uses a fair and reasonable default user permissions, but nevertheless you should read all
```

By reading the cfg.tbl you should have found the text about `additional scripts`.
