### ISSUE TITLE
Freshstuff

### ISSUE THREAD

**Issue by Havokdan** [luadch/scripts#17]
Good morning, would you like to know how I can edit and / or create more categories in this script? Because I would like to translate these plugins, put other categories, I even get the script to show these new categories, however when adding some file to a category that is not native to the script, it gives an error. Thank you in advance.

**Comment by Sopor-** [comment]
It is quiet easy if you open ptx_freshstuff.lua and ptx_freshstuff_categories.dat and see how it is made.
