### ISSUE TITLE
ptx_freshstuff_v0.8 (multi3) no rightclick menu

### ISSUE THREAD

**Issue by c0r4ir** [luadch/scripts#2]
OS: Ubuntu 16.04
Client: AirDC++ 3.42 
Client: ApexDC++ 1.6.4
Luadch v2.19
ptx_freshstuff_v0.8

This is a hub hosted by me. Right Click menu not appearing in client AirDC++. I also tried ApexDC++. I have not made any modifications to the .lua script. However, I am able to use freshstuff commands in the client. What can be the issue?

**Comment by Sopor-** [comment]
No error messages in the error.log?

**Comment by c0r4ir** [comment]
There are 3 entries in the error log but it is unrelated to the problem. I will post it just in case. 

[error.log](https://github.com/luadch/scripts/files/1682784/error.log)

**Comment by Sopor-** [comment]
I installed it into a clean Luadch and i got the menu so i have no idea why you don't get them.
Did you added `ptx_freshstuff.lua` below `--// add here your additional scripts` in the `cfg.tbl`?

**Comment by c0r4ir** [comment]
Sopor, i have ptx_freshstuff.lua correctly placed like so:

-// add here your additional scripts
"etc_onlinecounter.lua",
"etc_requests.lua",
"ptx_freshstuff.lua",
"etc_noadvertise.lua",

Wonder what it could be. Maybe i will try a fresh install.

**Comment by Sopor-** [comment]
It is quite easy to setup a local Luadch and add `ptx_freshstuff.lua` and see if it works.

**Comment by Sopor-** [comment]
And you are doing a +reload and you also need reconnect to load the new menus.

**Comment by c0r4ir** [comment]
i tried that. I even shutdown the server and restarted with no luck. At least freshstuff commands work in the client.

**Comment by Sopor-** [comment]
I have now tested a second time and it works perfect. The only thing i did in the cfg.tbl was to add the `ptx_freshstuff.lua` and of course copy all the files to the right folders.
```
        --------------------------------------

        --// add here your additional scripts

        "ptx_freshstuff.lua",


        --------------------------------------


        "hub_bot_cleaner.lua",  --  must be the second last script in the table

        "etc_unknown_command.lua",  -- must be the last script in the table

```

**Comment by Sopor-** [comment]
Is this still a problem?

**Comment by c0r4ir** [comment]
sorry for the late reply. it is working perfectly. Thank you for your time.
