### ISSUE TITLE
How do i enable right clicks?

### ISSUE THREAD

**Issue by HadesDCH** [luadch/scripts#20]
Not sure - but it doesnt work no matter what i do.

**Comment by Sopor** [comment]
Where? This is the scripts issue.

**Comment by HadesDCH** [comment]
dc++
Is there anything at all i have to edit in the script itself to enable r click?

**Comment by HadesDCH** [comment]
I'm talking about freshstuff script v8

**Comment by Sopor** [comment]
Where do you try to open this right click? If you are running DC++ you should right click in the hub tab at the top. Have you tried that?

**Comment by HadesDCH** [comment]
Oh.
Yeah hubtab works . Sorry i had no clue this is where it is. To me right click is usually accessible by r clicking on any username in the hub userlist. 
Anyway yes its working. Thanx for your help.
I think most dc users would look for it there not hubtab.
BTW.
Is there a chance to get a script that will display lines of text every x minutes in hub's topic?
I would really appreciate it.
