### ISSUE TITLE
etc_requests_v0.7 (multi)

### ISSUE THREAD

**Issue by apax0r** [luadch/scripts#3]
Hi, i have a small problem with this script.

This script only works in the Right click menu, not when using the commands like: +request showall that ends up with "Unknown command." notting in my logs, any ide?

i have the latest luadch

Nevermind, the issue is that the help says "+request showall" but it should be be "request show all"

This may be closed!

**Comment by Sopor-** [comment]
The correct command should be `+request showall` and `+request showdel`
