### ISSUE TITLE
etc_requests.lua - bad argument #1 to 'find'

### ISSUE THREAD

**Issue by Sopor** [luadch/scripts#4]
When running request without any release name from RC it will generate this error message and `Unknown command` will show up:
```
 scripts.lua: script error: ././scripts/etc_requests.lua:266: bad argument #1 to 'find' (string expected, got nil) (listener: onBroadcast; script: 'etc_requests.lua')
```
If i run `+request` in main it will show the help as it should do.

**Comment by Sopor-** [comment]
There are a few different scripts out of this etc_requests so the errors are not the same on ll versions.

**Comment by Sopor** [comment]
I have made a fix for it. Maybe i will upload it some day :)
